#! /usr/bin/env python2.6
# -*- coding: utf-8 -*-

from gspeett import gspeett

GOOGLE_API_KEY= "AIzaSyCjUiaoRKX7BZ6twcQj0yW1Y6ElstWeELA"

t = gspeett.GoogleTranslator(GOOGLE_API_KEY, to="en")

#print(str(t.translate("Donne moi la cassette vidéo")))
reco_en = gspeett.GoogleVoiceRecognition(gspeett.LANG_EN)
reco_fr = gspeett.GoogleVoiceRecognition(gspeett.LANG_FR)

#res = reco_fr.flac("donne_moi_la_cassette_video.flac")
res = reco_fr.mic()

for s in res:
    print("Got \"" + s + "\" in french -> ")
    print("\"" + t.translate(s) + "\" in english")

